//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatyeShopApp_SochnevRenat420.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatyeShopDBEntities : DbContext
    {
        public MatyeShopDBEntities()
            : base("name=MatyeShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Client_Service> Client_Service { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Qualification> Qualification { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceCollection> ServiceCollection { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
