//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatyeShopApp_SochnevRenat420.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Client_Service = new HashSet<Client_Service>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public Nullable<int> IdMaster { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IdServiceType { get; set; }
        public Nullable<int> IdServiceCollection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Service> Client_Service { get; set; }
        public virtual Master Master { get; set; }
        public virtual ServiceCollection ServiceCollection { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
